apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastdds-discovery-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sqe/robotics-k8s-infra
    targetRevision: main
    path: apps/base/fastdds-discovery-server
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ros2-talker-fastdds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sqe/robotics-k8s-infra
    targetRevision: main
    path: apps/base/ros2-talker
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ros2-listener-fastdds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sqe/robotics-k8s-infra
    targetRevision: main
    path: apps/base/ros2-listener
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
