---
# ROS 2 Talker Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ros2-talker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sqe/robotics-k8s-infra.git
    targetRevision: main
    path: apps/overlays/development/ros2-talker
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
# ROS 2 Listener Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ros2-listener
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sqe/robotics-k8s-infra.git
    targetRevision: main
    path: apps/overlays/development/ros2-listener
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
